name: master branch updated

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install poetry invoke
          inv env.init-dev -w

      # do not failed when there is not versioning needed (e.g., document change)
      - name: Create bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          inv git.bump -w

      - name: Push changes
        uses: Woile/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: "true"

  publish-github-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install pipenv invoke
          inv env.init-dev -w

      - name: Build docs
        run: |
          inv doc.build

      - name: Push doc to Github Page
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
